default_profile = "tamas"

[profiles.tamas]
user_id = "@tamas:bartatamas.hu"
url = "https://matrix.bartatamas.hu"

[settings]
username_display = "displayname"
image_preview = {}
message_user_color = true

[macros.normal]
"gc" = ":chats<Enter>"
"gss" = ":spaces<Enter>"
"guu" = ":unreads<Enter>"
"guc" = ":unreads clear<Enter>"

"rr" = ":reply<Enter>i"
"rh" = ":react â¤ï¸<Enter>"
"rl" = ":react ğŸ‘<Enter>"
"dd" = ":redact<Enter>"
